# Generated by Django 3.0.4 on 2020-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleaApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='%%defaultname%%', max_length=255),
            preserve_default=False,
        ),
    ]
