# Generated by Django 3.0.4 on 2020-03-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voleaApi', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isChecked',
        ),
        migrations.AlterField(
            model_name='item',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL),
        ),
    ]
