# Generated by Django 3.0.4 on 2020-03-25 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voleaApi', '0007_auto_20200318_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='sharedWith',
            field=models.ManyToManyField(blank=True, related_name='user_list', related_query_name='sharedWith', to=settings.AUTH_USER_MODEL),
        ),
    ]
