# Generated by Django 3.0.4 on 2020-04-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voleaApi', '0008_auto_20200325_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to='voleaApi.Profile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='voleaApi.Profile'),
        ),
        migrations.AlterField(
            model_name='list',
            name='sharedWith',
            field=models.ManyToManyField(blank=True, related_name='user_list', related_query_name='sharedWith', to='voleaApi.Profile'),
        ),
    ]
