# Generated by Django 3.0.4 on 2020-04-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voleaApi', '0009_auto_20200401_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voleaApi.Profile'),
        ),
    ]
