# Generated by Django 3.0.4 on 2020-04-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voleaApi', '0010_auto_20200401_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avater',
            new_name='avatar',
        ),
    ]
