# Generated by Django 3.0.4 on 2020-04-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleaApi', '0011_auto_20200402_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(),
        ),
    ]
