# Generated by Django 3.0.4 on 2020-04-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voleaApi', '0015_auto_20200403_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_checked', to='voleaApi.Profile'),
        ),
    ]
